version: 0.1
keywords: "HTML, Javascript, Visual Experience"
title: "Connection #1"
description: "Connection #1 is a part of visual experiences I had recently. It works with dots and straight line to create a illusion based on user interactions..."
url: "http://behrooz-tahanzadeh.github.io/connection-1/"
date: "August 2014"
